/**
 * Document Preview Page
 *
 * Server component that fetches a single generated document
 * and renders it with preview/download capabilities.
 *
 * Threat mitigations:
 * - T-05-12: Presigned URL generated server-side after project membership verification. 5-minute TTL.
 */

import Link from "next/link"
import { notFound } from "next/navigation"
import { format } from "date-fns"
import { ArrowLeft, Download } from "lucide-react"
import { getCurrentMember } from "@/lib/auth"
import { prisma } from "@/lib/db"
import { getDownloadUrl } from "@/lib/documents/s3-storage"
import { Button } from "@/components/ui/button"
import {
  DocumentPreview,
  type GeneratedDocumentDetail,
} from "@/components/documents/document-preview"

interface DocumentDetailPageProps {
  params: Promise<{ projectId: string; documentId: string }>
}

export default async function DocumentDetailPage({
  params,
}: DocumentDetailPageProps) {
  const { projectId, documentId } = await params

  // Auth check
  try {
    await getCurrentMember(projectId)
  } catch {
    notFound()
  }

  // Fetch document
  const doc = await prisma.generatedDocument.findUnique({
    where: { id: documentId },
    include: {
      generatedBy: {
        select: { displayName: true },
      },
    },
  })

  if (!doc || doc.projectId !== projectId) {
    notFound()
  }

  // Compute version number
  const docsOfType = await prisma.generatedDocument.findMany({
    where: { projectId, documentType: doc.documentType },
    orderBy: { createdAt: "asc" },
    select: { id: true },
  })
  const version = docsOfType.findIndex((d) => d.id === documentId) + 1

  // Get presigned download URL (T-05-12: 5-minute TTL)
  // Membership already verified above, so call s3-storage directly
  const downloadUrl = doc.s3Key ? await getDownloadUrl(doc.s3Key, 300) : ""

  const documentDetail: GeneratedDocumentDetail = {
    id: doc.id,
    title: doc.title,
    documentType: doc.documentType,
    format: doc.format,
    createdAt: doc.createdAt.toISOString(),
    generatedBy: doc.generatedBy,
  }

  const formatLabel =
    doc.format === "DOCX" ? "Word" : doc.format === "PPTX" ? "PowerPoint" : "PDF"

  return (
    <div>
      {/* Back link */}
      <Link
        href={`/projects/${projectId}/documents`}
        className="inline-flex items-center gap-1 text-[14px] text-muted-foreground hover:text-foreground transition-colors mb-4"
      >
        <ArrowLeft className="h-4 w-4" />
        Back to Documents
      </Link>

      {/* Header */}
      <div className="flex items-start justify-between mb-6">
        <div>
          <h1 className="text-[24px] font-semibold text-foreground">
            {doc.title} v{version}
          </h1>
          <p className="text-[13px] text-muted-foreground mt-1">
            Generated by {doc.generatedBy?.displayName ?? "Unknown"} on{" "}
            {format(doc.createdAt, "MMM d, yyyy")}
          </p>
        </div>

        {downloadUrl && (
          <Button asChild className="bg-[#2563EB] hover:bg-[#1d4ed8] text-white">
            <a href={downloadUrl} target="_blank" rel="noopener noreferrer">
              <Download className="h-4 w-4" />
              Download {formatLabel}
            </a>
          </Button>
        )}
      </div>

      {/* Preview */}
      {downloadUrl ? (
        <DocumentPreview document={documentDetail} downloadUrl={downloadUrl} />
      ) : (
        <p className="text-[14px] text-muted-foreground">
          Download URL is not available. The document may still be generating.
        </p>
      )}
    </div>
  )
}
