"use client"

/**
 * Version History Table
 *
 * Displays generated documents in a table with version numbers,
 * download actions, and preview links.
 */

import { useRouter } from "next/navigation"
import { Download } from "lucide-react"
import { format } from "date-fns"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table"
import { EmptyState } from "@/components/shared/empty-state"

export interface GeneratedDocumentRow {
  id: string
  title: string
  documentType: string
  format: string
  version: number
  createdAt: string | Date
  generatedBy: { displayName: string | null }
}

interface VersionHistoryTableProps {
  documents: GeneratedDocumentRow[]
  projectId: string
  onDownload: (documentId: string) => void
}

const FORMAT_LABELS: Record<string, string> = {
  DOCX: "Word",
  PPTX: "PowerPoint",
  PDF: "PDF",
}

export function VersionHistoryTable({
  documents,
  projectId,
  onDownload,
}: VersionHistoryTableProps) {
  const router = useRouter()

  if (documents.length === 0) {
    return (
      <EmptyState
        heading="No documents generated"
        description="Generate branded deliverables from your project's knowledge base. Choose a template to get started."
      />
    )
  }

  return (
    <Table>
      <TableHeader>
        <TableRow>
          <TableHead>Template</TableHead>
          <TableHead>Version</TableHead>
          <TableHead>Generated By</TableHead>
          <TableHead>Date</TableHead>
          <TableHead>Format</TableHead>
          <TableHead className="text-right">Actions</TableHead>
        </TableRow>
      </TableHeader>
      <TableBody>
        {documents.map((doc) => (
          <TableRow key={doc.id}>
            <TableCell className="text-[14px] font-normal">
              {doc.title}
            </TableCell>
            <TableCell className="text-[13px] text-muted-foreground">
              v{doc.version}
            </TableCell>
            <TableCell className="text-[14px] font-normal">
              {doc.generatedBy?.displayName ?? "Unknown"}
            </TableCell>
            <TableCell className="text-[13px] text-muted-foreground">
              {format(new Date(doc.createdAt), "MMM d, yyyy")}
            </TableCell>
            <TableCell>
              <Badge variant="secondary">
                {FORMAT_LABELS[doc.format] ?? doc.format}
              </Badge>
            </TableCell>
            <TableCell className="text-right">
              <div className="flex items-center justify-end gap-2">
                <Button
                  variant="ghost"
                  size="icon"
                  onClick={() => onDownload(doc.id)}
                  title="Download"
                >
                  <Download className="h-4 w-4" />
                </Button>
                <Button
                  variant="link"
                  size="sm"
                  onClick={() =>
                    router.push(
                      `/projects/${projectId}/documents/${doc.id}`
                    )
                  }
                >
                  Preview
                </Button>
              </div>
            </TableCell>
          </TableRow>
        ))}
      </TableBody>
    </Table>
  )
}
